ifneq (,$(filter saul_default,$(USEMODULE)))
    USEMODULE += saul_gpio
    USEMODULE += si70xx
endif
ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
    USEMODULE += rail
endif 

include $(RIOTCPU)/efm32/Makefile.dep
